spring:
  application:
    name: garage-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/garage_db
    username: garage_app
    password: karmakaze69
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    jwt:
      secret: your-256-bit-secret-key-here-change-in-production
      expiration: 86400000 # 24 hours in milliseconds
      refresh-expiration: 604800000 # 7 days in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.garage.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# AWS Configuration (for future use)
aws:
  region: us-east-1
  s3:
    bucket-name: garage-management-bucket 