spring:
  application:
    name: garage-backend
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration
  
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: true

logging:
  level:
    com.garage.backend: ${LOGGING_LEVEL}
    org.springframework.security: ${LOGGING_LEVEL}
    org.hibernate.SQL: ${LOGGING_LEVEL}
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: ${LOGGING_LEVEL}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME} 