spring:
  application:
    name: garage-backend
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/garage_db}
    username: ${DB_USERNAME:garage_app}
    password: ${DB_PASSWORD:karmakaze69}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration
  
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-here-change-in-production}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

  mail:
    host: smtp.gmail.com
    port: 587
    username: karmanyasingh8@gmail.com
    password: ${GMAIL_APP_PASSWORD:your_gmail_app_password_here}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: true

logging:
  level:
    com.garage.backend: ${LOGGING_LEVEL:DEBUG}
    org.springframework.security: ${LOGGING_LEVEL:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: ${LOGGING_LEVEL:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# AWS Configuration (for future use)
aws:
  region: us-east-1
  s3:
    bucket-name: garage-management-bucket 